dist: xenial   # required for Python >= 3.7
os: linux
sudo: false
language: python
python:
  - "3.6"
  - "3.7"

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      python: 3.8
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: test
      install:
        - pip install poetry
        - poetry install -v
      script:
        - poetry run pytest

after_sucess:
  - poetry run coveralls
