dist: xenial   # required for Python >= 3.7
os: linux
sudo: false
language: python
python:
  - "3.6"
  - "3.7"

stages:
  - lint
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - poetry run pytest
      after_sucess:
        - poetry run coveralls
