dist: xenial   # required for Python >= 3.7
os: linux
sudo: false
language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - poetry run pytest
after_sucess:
  - poetry run coveralls
