os: linux
sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
#  - pip install psychrochart
  - pip install .
  - pip install pytest coverage pytest-cov
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script:
  - py.test tests --cov=psychrochart -v --cov-report html

after_sucess:
  coveralls