[tool.poetry]
name = "psychrochart"
version = "0.3.0a"
description = "A python 3 library to make psychrometric charts and overlay information on them"
authors = ["Eugenio Panadero <eugenio.panadero@gmail.com>"]
packages = [
    { include = "psychrochart" }
]
readme = "README.md"
repository = "https://github.com/azogue/psychrochart"

[tool.poetry.dependencies]
python = "^3.7"
matplotlib = "^3.1"
scipy = "^1.3"
psychrolib = "^2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-sugar = "^0.9.2"
pytest-cov = "^2.7"
coveralls = "^1.8"

[tool.black]
exclude = "^.*/charts/.*$"
line-length = 79
target-version = ["py37"]
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
